server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      defualtZone: http://${eureka.instance.hostname}:${server.port}/eureka/