server:
  port: 8083

spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: provider-service-feign

eureka:
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"
  health:
    show-details: always


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
