server:
  port: 8040

spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: mc-movie-gateway-zuul

eureka:
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8000/eureka/